name: inquire
description: Get to truly know yourself & other people.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  go_router: ^3.1.0
  json_annotation: ^4.5.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/questions/
